# Metodo get se chamar uma chave que n達o existe e n達o gera erro
contatos = {"gui@gmail.com": {"nome": "Guilherme", "telefone": "3333-2221"}}

#print(contatos["chave"]) # >>> KeyError: 'chave' chave n達o existe 

print(contatos.get("chave")) 
print(contatos.get("chave",{}))
print(contatos.get("gui@gmail.com",{})) # Essa chave contem
print(contatos.get("guilherme@gmail.com",{}))  #Essa chave n達o contem e retorna vazio


